/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// ActionOneOf2
    /// </summary>
    [DataContract(Name = "Action_oneOf_2")]
    public partial class ActionOneOf2 : IEquatable<ActionOneOf2>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionOneOf2" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActionOneOf2() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionOneOf2" /> class.
        /// </summary>
        /// <param name="notifyIf">notifyIf (required).</param>
        public ActionOneOf2(Observation notifyIf = default(Observation))
        {
            // to ensure "notifyIf" is required (not null)
            if (notifyIf == null)
            {
                throw new ArgumentNullException("notifyIf is a required property for ActionOneOf2 and cannot be null");
            }
            this._NotifyIf = notifyIf;
        }

        /// <summary>
        /// Gets or Sets NotifyIf
        /// </summary>
        [DataMember(Name = "notify_if", IsRequired = true, EmitDefaultValue = true)]
        public Observation NotifyIf
        {
            get{ return _NotifyIf;}
            set
            {
                _NotifyIf = value;
                _flagNotifyIf = true;
            }
        }
        private Observation _NotifyIf;
        private bool _flagNotifyIf;

        /// <summary>
        /// Returns false as NotifyIf should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNotifyIf()
        {
            return _flagNotifyIf;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActionOneOf2 {\n");
            sb.Append("  NotifyIf: ").Append(NotifyIf).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ActionOneOf2);
        }

        /// <summary>
        /// Returns true if ActionOneOf2 instances are equal
        /// </summary>
        /// <param name="input">Instance of ActionOneOf2 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ActionOneOf2 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NotifyIf == input.NotifyIf ||
                    (this.NotifyIf != null &&
                    this.NotifyIf.Equals(input.NotifyIf))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NotifyIf != null)
                {
                    hashCode = (hashCode * 59) + this.NotifyIf.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
