/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// ContractsContractIdTransactionsTransactionIdGet200ResponseLinks
    /// </summary>
    [DataContract(Name = "_contracts__contractId__transactions__transactionId__get_200_response_links")]
    public partial class ContractsContractIdTransactionsTransactionIdGet200ResponseLinks : IEquatable<ContractsContractIdTransactionsTransactionIdGet200ResponseLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContractsContractIdTransactionsTransactionIdGet200ResponseLinks" /> class.
        /// </summary>
        /// <param name="next">next.</param>
        /// <param name="previous">previous.</param>
        public ContractsContractIdTransactionsTransactionIdGet200ResponseLinks(string next = default(string), string previous = default(string))
        {
            this._Next = next;
            if (this.Next != null)
            {
                this._flagNext = true;
            }
            this._Previous = previous;
            if (this.Previous != null)
            {
                this._flagPrevious = true;
            }
        }

        /// <summary>
        /// Gets or Sets Next
        /// </summary>
        [DataMember(Name = "next", EmitDefaultValue = false)]
        public string Next
        {
            get{ return _Next;}
            set
            {
                _Next = value;
                _flagNext = true;
            }
        }
        private string _Next;
        private bool _flagNext;

        /// <summary>
        /// Returns false as Next should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNext()
        {
            return _flagNext;
        }
        /// <summary>
        /// Gets or Sets Previous
        /// </summary>
        [DataMember(Name = "previous", EmitDefaultValue = false)]
        public string Previous
        {
            get{ return _Previous;}
            set
            {
                _Previous = value;
                _flagPrevious = true;
            }
        }
        private string _Previous;
        private bool _flagPrevious;

        /// <summary>
        /// Returns false as Previous should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrevious()
        {
            return _flagPrevious;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContractsContractIdTransactionsTransactionIdGet200ResponseLinks {\n");
            sb.Append("  Next: ").Append(Next).Append("\n");
            sb.Append("  Previous: ").Append(Previous).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ContractsContractIdTransactionsTransactionIdGet200ResponseLinks);
        }

        /// <summary>
        /// Returns true if ContractsContractIdTransactionsTransactionIdGet200ResponseLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of ContractsContractIdTransactionsTransactionIdGet200ResponseLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContractsContractIdTransactionsTransactionIdGet200ResponseLinks input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Next == input.Next ||
                    (this.Next != null &&
                    this.Next.Equals(input.Next))
                ) && 
                (
                    this.Previous == input.Previous ||
                    (this.Previous != null &&
                    this.Previous.Equals(input.Previous))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Next != null)
                {
                    hashCode = (hashCode * 59) + this.Next.GetHashCode();
                }
                if (this.Previous != null)
                {
                    hashCode = (hashCode * 59) + this.Previous.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
