/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// IntervalInPastIntervalInPastError
    /// </summary>
    [DataContract(Name = "IntervalInPast_intervalInPastError")]
    public partial class IntervalInPastIntervalInPastError : IEquatable<IntervalInPastIntervalInPastError>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IntervalInPastIntervalInPastError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IntervalInPastIntervalInPastError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IntervalInPastIntervalInPastError" /> class.
        /// </summary>
        /// <param name="from">from (required).</param>
        /// <param name="minTime">minTime (required).</param>
        /// <param name="to">to (required).</param>
        public IntervalInPastIntervalInPastError(int from = default(int), int minTime = default(int), int to = default(int))
        {
            this._From = from;
            this._MinTime = minTime;
            this._To = to;
        }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        [DataMember(Name = "from", IsRequired = true, EmitDefaultValue = true)]
        public int From
        {
            get{ return _From;}
            set
            {
                _From = value;
                _flagFrom = true;
            }
        }
        private int _From;
        private bool _flagFrom;

        /// <summary>
        /// Returns false as From should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFrom()
        {
            return _flagFrom;
        }
        /// <summary>
        /// Gets or Sets MinTime
        /// </summary>
        [DataMember(Name = "minTime", IsRequired = true, EmitDefaultValue = true)]
        public int MinTime
        {
            get{ return _MinTime;}
            set
            {
                _MinTime = value;
                _flagMinTime = true;
            }
        }
        private int _MinTime;
        private bool _flagMinTime;

        /// <summary>
        /// Returns false as MinTime should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMinTime()
        {
            return _flagMinTime;
        }
        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [DataMember(Name = "to", IsRequired = true, EmitDefaultValue = true)]
        public int To
        {
            get{ return _To;}
            set
            {
                _To = value;
                _flagTo = true;
            }
        }
        private int _To;
        private bool _flagTo;

        /// <summary>
        /// Returns false as To should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTo()
        {
            return _flagTo;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IntervalInPastIntervalInPastError {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  MinTime: ").Append(MinTime).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IntervalInPastIntervalInPastError);
        }

        /// <summary>
        /// Returns true if IntervalInPastIntervalInPastError instances are equal
        /// </summary>
        /// <param name="input">Instance of IntervalInPastIntervalInPastError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IntervalInPastIntervalInPastError input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.From == input.From ||
                    this.From.Equals(input.From)
                ) && 
                (
                    this.MinTime == input.MinTime ||
                    this.MinTime.Equals(input.MinTime)
                ) && 
                (
                    this.To == input.To ||
                    this.To.Equals(input.To)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.From.GetHashCode();
                hashCode = (hashCode * 59) + this.MinTime.GetHashCode();
                hashCode = (hashCode * 59) + this.To.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
