/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// Bind a value to a name within the scope of a sub-contract.
    /// </summary>
    [DataContract(Name = "LetObject")]
    public partial class LetObject : IEquatable<LetObject>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LetObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LetObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LetObject" /> class.
        /// </summary>
        /// <param name="be">be (required).</param>
        /// <param name="let">let (required).</param>
        /// <param name="then">then (required).</param>
        public LetObject(ValueObject be = default(ValueObject), string let = default(string), ContractObject then = default(ContractObject))
        {
            // to ensure "be" is required (not null)
            if (be == null)
            {
                throw new ArgumentNullException("be is a required property for LetObject and cannot be null");
            }
            this.Be = be;
            // to ensure "let" is required (not null)
            if (let == null)
            {
                throw new ArgumentNullException("let is a required property for LetObject and cannot be null");
            }
            this.Let = let;
            // to ensure "then" is required (not null)
            if (then == null)
            {
                throw new ArgumentNullException("then is a required property for LetObject and cannot be null");
            }
            this.Then = then;
        }

        /// <summary>
        /// Gets or Sets Be
        /// </summary>
        [DataMember(Name = "be", IsRequired = true, EmitDefaultValue = true)]
        public ValueObject Be { get; set; }

        /// <summary>
        /// Gets or Sets Let
        /// </summary>
        [DataMember(Name = "let", IsRequired = true, EmitDefaultValue = true)]
        public string Let { get; set; }

        /// <summary>
        /// Gets or Sets Then
        /// </summary>
        [DataMember(Name = "then", IsRequired = true, EmitDefaultValue = true)]
        public ContractObject Then { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LetObject {\n");
            sb.Append("  Be: ").Append(Be).Append("\n");
            sb.Append("  Let: ").Append(Let).Append("\n");
            sb.Append("  Then: ").Append(Then).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LetObject);
        }

        /// <summary>
        /// Returns true if LetObject instances are equal
        /// </summary>
        /// <param name="input">Instance of LetObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LetObject input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Be == input.Be ||
                    (this.Be != null &&
                    this.Be.Equals(input.Be))
                ) && 
                (
                    this.Let == input.Let ||
                    (this.Let != null &&
                    this.Let.Equals(input.Let))
                ) && 
                (
                    this.Then == input.Then ||
                    (this.Then != null &&
                    this.Then.Equals(input.Then))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Be != null)
                {
                    hashCode = (hashCode * 59) + this.Be.GetHashCode();
                }
                if (this.Let != null)
                {
                    hashCode = (hashCode * 59) + this.Let.GetHashCode();
                }
                if (this.Then != null)
                {
                    hashCode = (hashCode * 59) + this.Then.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
