/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// Refers to a party by role name.
    /// </summary>
    [DataContract(Name = "PartyRoleName")]
    public partial class PartyRoleName : IEquatable<PartyRoleName>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyRoleName" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PartyRoleName() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyRoleName" /> class.
        /// </summary>
        /// <param name="roleToken">roleToken (required).</param>
        public PartyRoleName(string roleToken = default(string))
        {
            // to ensure "roleToken" is required (not null)
            if (roleToken == null)
            {
                throw new ArgumentNullException("roleToken is a required property for PartyRoleName and cannot be null");
            }
            this.RoleToken = roleToken;
        }

        /// <summary>
        /// Gets or Sets RoleToken
        /// </summary>
        [DataMember(Name = "role_token", IsRequired = true, EmitDefaultValue = true)]
        public string RoleToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartyRoleName {\n");
            sb.Append("  RoleToken: ").Append(RoleToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PartyRoleName);
        }

        /// <summary>
        /// Returns true if PartyRoleName instances are equal
        /// </summary>
        /// <param name="input">Instance of PartyRoleName to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PartyRoleName input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RoleToken == input.RoleToken ||
                    (this.RoleToken != null &&
                    this.RoleToken.Equals(input.RoleToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RoleToken != null)
                {
                    hashCode = (hashCode * 59) + this.RoleToken.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
