/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// Defines TimeInterval
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TimeInterval
    {
        /// <summary>
        /// Enum Start for value: time_interval_start
        /// </summary>
        [EnumMember(Value = "time_interval_start")]
        Start = 1,

        /// <summary>
        /// Enum End for value: time_interval_end
        /// </summary>
        [EnumMember(Value = "time_interval_end")]
        End = 2
    }

}
