/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// ValueObjectOneOf8
    /// </summary>
    [DataContract(Name = "ValueObject_oneOf_8")]
    public partial class ValueObjectOneOf8 : IEquatable<ValueObjectOneOf8>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObjectOneOf8" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ValueObjectOneOf8() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObjectOneOf8" /> class.
        /// </summary>
        /// <param name="varRef">An arbitrary text identifier for an object in a Marlowe object bundle. (required).</param>
        public ValueObjectOneOf8(string varRef = default(string))
        {
            // to ensure "varRef" is required (not null)
            if (varRef == null)
            {
                throw new ArgumentNullException("varRef is a required property for ValueObjectOneOf8 and cannot be null");
            }
            this._VarRef = varRef;
        }

        /// <summary>
        /// An arbitrary text identifier for an object in a Marlowe object bundle.
        /// </summary>
        /// <value>An arbitrary text identifier for an object in a Marlowe object bundle.</value>
        [DataMember(Name = "ref", IsRequired = true, EmitDefaultValue = true)]
        public string VarRef
        {
            get{ return _VarRef;}
            set
            {
                _VarRef = value;
                _flagVarRef = true;
            }
        }
        private string _VarRef;
        private bool _flagVarRef;

        /// <summary>
        /// Returns false as VarRef should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeVarRef()
        {
            return _flagVarRef;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValueObjectOneOf8 {\n");
            sb.Append("  VarRef: ").Append(VarRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValueObjectOneOf8);
        }

        /// <summary>
        /// Returns true if ValueObjectOneOf8 instances are equal
        /// </summary>
        /// <param name="input">Instance of ValueObjectOneOf8 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValueObjectOneOf8 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.VarRef == input.VarRef ||
                    (this.VarRef != null &&
                    this.VarRef.Equals(input.VarRef))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VarRef != null)
                {
                    hashCode = (hashCode * 59) + this.VarRef.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
