/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// ValueObjectOneOf4
    /// </summary>
    [DataContract(Name = "ValueObject_oneOf_4")]
    public partial class ValueObjectOneOf4 : IEquatable<ValueObjectOneOf4>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObjectOneOf4" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ValueObjectOneOf4() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObjectOneOf4" /> class.
        /// </summary>
        /// <param name="multiply">multiply (required).</param>
        /// <param name="times">times (required).</param>
        public ValueObjectOneOf4(ValueObject multiply = default(ValueObject), ValueObject times = default(ValueObject))
        {
            // to ensure "multiply" is required (not null)
            if (multiply == null)
            {
                throw new ArgumentNullException("multiply is a required property for ValueObjectOneOf4 and cannot be null");
            }
            this._Multiply = multiply;
            // to ensure "times" is required (not null)
            if (times == null)
            {
                throw new ArgumentNullException("times is a required property for ValueObjectOneOf4 and cannot be null");
            }
            this._Times = times;
        }

        /// <summary>
        /// Gets or Sets Multiply
        /// </summary>
        [DataMember(Name = "multiply", IsRequired = true, EmitDefaultValue = true)]
        public ValueObject Multiply
        {
            get{ return _Multiply;}
            set
            {
                _Multiply = value;
                _flagMultiply = true;
            }
        }
        private ValueObject _Multiply;
        private bool _flagMultiply;

        /// <summary>
        /// Returns false as Multiply should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMultiply()
        {
            return _flagMultiply;
        }
        /// <summary>
        /// Gets or Sets Times
        /// </summary>
        [DataMember(Name = "times", IsRequired = true, EmitDefaultValue = true)]
        public ValueObject Times
        {
            get{ return _Times;}
            set
            {
                _Times = value;
                _flagTimes = true;
            }
        }
        private ValueObject _Times;
        private bool _flagTimes;

        /// <summary>
        /// Returns false as Times should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTimes()
        {
            return _flagTimes;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValueObjectOneOf4 {\n");
            sb.Append("  Multiply: ").Append(Multiply).Append("\n");
            sb.Append("  Times: ").Append(Times).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValueObjectOneOf4);
        }

        /// <summary>
        /// Returns true if ValueObjectOneOf4 instances are equal
        /// </summary>
        /// <param name="input">Instance of ValueObjectOneOf4 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValueObjectOneOf4 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Multiply == input.Multiply ||
                    (this.Multiply != null &&
                    this.Multiply.Equals(input.Multiply))
                ) && 
                (
                    this.Times == input.Times ||
                    (this.Times != null &&
                    this.Times.Equals(input.Times))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Multiply != null)
                {
                    hashCode = (hashCode * 59) + this.Multiply.GetHashCode();
                }
                if (this.Times != null)
                {
                    hashCode = (hashCode * 59) + this.Times.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
