/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MarloweAPIClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace MarloweAPIClient.Model
{
    /// <summary>
    /// A time-varying expression that evaluates to a boolean
    /// </summary>
    [JsonConverter(typeof(ValueObjectJsonConverter))]
    [DataContract(Name = "ValueObject")]
    public partial class ValueObject : AbstractOpenAPISchema, IEquatable<ValueObject>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf.</param>
        public ValueObject(ValueObjectOneOf actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="long" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of long.</param>
        public ValueObject(long actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf1.</param>
        public ValueObject(ValueObjectOneOf1 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf2.</param>
        public ValueObject(ValueObjectOneOf2 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf3" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf3.</param>
        public ValueObject(ValueObjectOneOf3 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf4" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf4.</param>
        public ValueObject(ValueObjectOneOf4 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf5" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf5.</param>
        public ValueObject(ValueObjectOneOf5 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf6" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf6.</param>
        public ValueObject(ValueObjectOneOf6 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public ValueObject(string actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueOneOf7" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueOneOf7.</param>
        public ValueObject(ValueOneOf7 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf7" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf7.</param>
        public ValueObject(ValueObjectOneOf7 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValueObject" /> class
        /// with the <see cref="ValueObjectOneOf8" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueObjectOneOf8.</param>
        public ValueObject(ValueObjectOneOf8 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ValueObjectOneOf))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf1))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf2))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf3))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf4))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf5))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf6))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf7))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueObjectOneOf8))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueOneOf7))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(long))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(string))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ValueObjectOneOf, ValueObjectOneOf1, ValueObjectOneOf2, ValueObjectOneOf3, ValueObjectOneOf4, ValueObjectOneOf5, ValueObjectOneOf6, ValueObjectOneOf7, ValueObjectOneOf8, ValueOneOf7, long, string");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf`. If the actual instance is not `ValueObjectOneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf</returns>
        public ValueObjectOneOf GetValueObjectOneOf()
        {
            return (ValueObjectOneOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `long`. If the actual instance is not `long`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of long</returns>
        public long GetLong()
        {
            return (long)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf1`. If the actual instance is not `ValueObjectOneOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf1</returns>
        public ValueObjectOneOf1 GetValueObjectOneOf1()
        {
            return (ValueObjectOneOf1)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf2`. If the actual instance is not `ValueObjectOneOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf2</returns>
        public ValueObjectOneOf2 GetValueObjectOneOf2()
        {
            return (ValueObjectOneOf2)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf3`. If the actual instance is not `ValueObjectOneOf3`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf3</returns>
        public ValueObjectOneOf3 GetValueObjectOneOf3()
        {
            return (ValueObjectOneOf3)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf4`. If the actual instance is not `ValueObjectOneOf4`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf4</returns>
        public ValueObjectOneOf4 GetValueObjectOneOf4()
        {
            return (ValueObjectOneOf4)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf5`. If the actual instance is not `ValueObjectOneOf5`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf5</returns>
        public ValueObjectOneOf5 GetValueObjectOneOf5()
        {
            return (ValueObjectOneOf5)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf6`. If the actual instance is not `ValueObjectOneOf6`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf6</returns>
        public ValueObjectOneOf6 GetValueObjectOneOf6()
        {
            return (ValueObjectOneOf6)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `string`. If the actual instance is not `string`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueOneOf7`. If the actual instance is not `ValueOneOf7`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueOneOf7</returns>
        public ValueOneOf7 GetValueOneOf7()
        {
            return (ValueOneOf7)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf7`. If the actual instance is not `ValueObjectOneOf7`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf7</returns>
        public ValueObjectOneOf7 GetValueObjectOneOf7()
        {
            return (ValueObjectOneOf7)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValueObjectOneOf8`. If the actual instance is not `ValueObjectOneOf8`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueObjectOneOf8</returns>
        public ValueObjectOneOf8 GetValueObjectOneOf8()
        {
            return (ValueObjectOneOf8)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValueObject {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ValueObject.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ValueObject
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ValueObject</returns>
        public static ValueObject FromJson(string jsonString)
        {
            ValueObject newValueObject = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newValueObject;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf1).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf1>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf1>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf1");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf2).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf2>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf2>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf2");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf2: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf3).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf3>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf3>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf3");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf3: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf4).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf4>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf4>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf4");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf4: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf5).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf5>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf5>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf5");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf5: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf6).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf6>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf6>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf6");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf6: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf7).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf7>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf7>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf7");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf7: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueObjectOneOf8).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf8>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueObjectOneOf8>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueObjectOneOf8");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueObjectOneOf8: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValueOneOf7).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueOneOf7>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<ValueOneOf7>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValueOneOf7");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueOneOf7: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(long).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<long>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<long>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("long");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into long: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(string).GetProperty("AdditionalProperties") == null)
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<string>(jsonString, ValueObject.SerializerSettings));
                }
                else
                {
                    newValueObject = new ValueObject(JsonConvert.DeserializeObject<string>(jsonString, ValueObject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("string");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into string: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newValueObject;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValueObject);
        }

        /// <summary>
        /// Returns true if ValueObject instances are equal
        /// </summary>
        /// <param name="input">Instance of ValueObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValueObject input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ValueObject
    /// </summary>
    public class ValueObjectJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ValueObject).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ValueObject.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
