/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing AddressAndMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressAndMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressAndMetadata
        //private AddressAndMetadata instance;

        public AddressAndMetadataTests()
        {
            // TODO uncomment below to create an instance of AddressAndMetadata
            //instance = new AddressAndMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressAndMetadata
        /// </summary>
        [Fact]
        public void AddressAndMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressAndMetadata
            //Assert.IsType<AddressAndMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
