/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing Assets
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Assets
        //private Assets instance;

        public AssetsTests()
        {
            // TODO uncomment below to create an instance of Assets
            //instance = new Assets();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Assets
        /// </summary>
        [Fact]
        public void AssetsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Assets
            //Assert.IsType<Assets>(instance);
        }

        /// <summary>
        /// Test the property 'Lovelace'
        /// </summary>
        [Fact]
        public void LovelaceTest()
        {
            // TODO unit test for the property 'Lovelace'
        }

        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }
    }
}
