/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing CaseObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CaseObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CaseObject
        //private CaseObject instance;

        public CaseObjectTests()
        {
            // TODO uncomment below to create an instance of CaseObject
            //instance = new CaseObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CaseObject
        /// </summary>
        [Fact]
        public void CaseObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" CaseObject
            //Assert.IsType<CaseObject>(instance);
        }

        /// <summary>
        /// Test the property 'VarCase'
        /// </summary>
        [Fact]
        public void VarCaseTest()
        {
            // TODO unit test for the property 'VarCase'
        }

        /// <summary>
        /// Test the property 'Then'
        /// </summary>
        [Fact]
        public void ThenTest()
        {
            // TODO unit test for the property 'Then'
        }

        /// <summary>
        /// Test the property 'MerkleizedThen'
        /// </summary>
        [Fact]
        public void MerkleizedThenTest()
        {
            // TODO unit test for the property 'MerkleizedThen'
        }
    }
}
