/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing CloseObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloseObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloseObject
        //private CloseObject instance;

        public CloseObjectTests()
        {
            // TODO uncomment below to create an instance of CloseObject
            //instance = new CloseObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloseObject
        /// </summary>
        [Fact]
        public void CloseObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" CloseObject
            //Assert.IsType<CloseObject>(instance);
        }
    }
}
