/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing DepositContinuationInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DepositContinuationInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DepositContinuationInput
        //private DepositContinuationInput instance;

        public DepositContinuationInputTests()
        {
            // TODO uncomment below to create an instance of DepositContinuationInput
            //instance = new DepositContinuationInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DepositContinuationInput
        /// </summary>
        [Fact]
        public void DepositContinuationInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" DepositContinuationInput
            //Assert.IsType<DepositContinuationInput>(instance);
        }

        /// <summary>
        /// Test the property 'ContinuationHash'
        /// </summary>
        [Fact]
        public void ContinuationHashTest()
        {
            // TODO unit test for the property 'ContinuationHash'
        }

        /// <summary>
        /// Test the property 'InputFromParty'
        /// </summary>
        [Fact]
        public void InputFromPartyTest()
        {
            // TODO unit test for the property 'InputFromParty'
        }

        /// <summary>
        /// Test the property 'IntoAccount'
        /// </summary>
        [Fact]
        public void IntoAccountTest()
        {
            // TODO unit test for the property 'IntoAccount'
        }

        /// <summary>
        /// Test the property 'MerkleizedContinuation'
        /// </summary>
        [Fact]
        public void MerkleizedContinuationTest()
        {
            // TODO unit test for the property 'MerkleizedContinuation'
        }

        /// <summary>
        /// Test the property 'OfToken'
        /// </summary>
        [Fact]
        public void OfTokenTest()
        {
            // TODO unit test for the property 'OfToken'
        }

        /// <summary>
        /// Test the property 'ThatDeposits'
        /// </summary>
        [Fact]
        public void ThatDepositsTest()
        {
            // TODO unit test for the property 'ThatDeposits'
        }
    }
}
