/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing GetTransactionResponseLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetTransactionResponseLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetTransactionResponseLinks
        //private GetTransactionResponseLinks instance;

        public GetTransactionResponseLinksTests()
        {
            // TODO uncomment below to create an instance of GetTransactionResponseLinks
            //instance = new GetTransactionResponseLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetTransactionResponseLinks
        /// </summary>
        [Fact]
        public void GetTransactionResponseLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetTransactionResponseLinks
            //Assert.IsType<GetTransactionResponseLinks>(instance);
        }

        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Fact]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
    }
}
