/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing LesserOrEqual
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LesserOrEqualTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LesserOrEqual
        //private LesserOrEqual instance;

        public LesserOrEqualTests()
        {
            // TODO uncomment below to create an instance of LesserOrEqual
            //instance = new LesserOrEqual();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LesserOrEqual
        /// </summary>
        [Fact]
        public void LesserOrEqualInstanceTest()
        {
            // TODO uncomment below to test "IsType" LesserOrEqual
            //Assert.IsType<LesserOrEqual>(instance);
        }

        /// <summary>
        /// Test the property 'LeThan'
        /// </summary>
        [Fact]
        public void LeThanTest()
        {
            // TODO unit test for the property 'LeThan'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
