/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing MetadataAndRecipients
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetadataAndRecipientsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetadataAndRecipients
        //private MetadataAndRecipients instance;

        public MetadataAndRecipientsTests()
        {
            // TODO uncomment below to create an instance of MetadataAndRecipients
            //instance = new MetadataAndRecipients();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetadataAndRecipients
        /// </summary>
        [Fact]
        public void MetadataAndRecipientsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetadataAndRecipients
            //Assert.IsType<MetadataAndRecipients>(instance);
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Fact]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
    }
}
