/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing Metadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Metadata
        //private Metadata instance;

        public MetadataTests()
        {
            // TODO uncomment below to create an instance of Metadata
            //instance = new Metadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Metadata
        /// </summary>
        [Fact]
        public void MetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" Metadata
            //Assert.IsType<Metadata>(instance);
        }
    }
}
