/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing NotifyAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotifyActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotifyAction
        //private NotifyAction instance;

        public NotifyActionTests()
        {
            // TODO uncomment below to create an instance of NotifyAction
            //instance = new NotifyAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotifyAction
        /// </summary>
        [Fact]
        public void NotifyActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotifyAction
            //Assert.IsType<NotifyAction>(instance);
        }

        /// <summary>
        /// Test the property 'NotifyIf'
        /// </summary>
        [Fact]
        public void NotifyIfTest()
        {
            // TODO unit test for the property 'NotifyIf'
        }
    }
}
