/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing Observation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObservationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Observation
        //private Observation instance;

        public ObservationTests()
        {
            // TODO uncomment below to create an instance of Observation
            //instance = new Observation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Observation
        /// </summary>
        [Fact]
        public void ObservationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Observation
            //Assert.IsType<Observation>(instance);
        }

        /// <summary>
        /// Test the property 'And'
        /// </summary>
        [Fact]
        public void AndTest()
        {
            // TODO unit test for the property 'And'
        }

        /// <summary>
        /// Test the property 'Both'
        /// </summary>
        [Fact]
        public void BothTest()
        {
            // TODO unit test for the property 'Both'
        }

        /// <summary>
        /// Test the property 'Either'
        /// </summary>
        [Fact]
        public void EitherTest()
        {
            // TODO unit test for the property 'Either'
        }

        /// <summary>
        /// Test the property 'Or'
        /// </summary>
        [Fact]
        public void OrTest()
        {
            // TODO unit test for the property 'Or'
        }

        /// <summary>
        /// Test the property 'Not'
        /// </summary>
        [Fact]
        public void NotTest()
        {
            // TODO unit test for the property 'Not'
        }

        /// <summary>
        /// Test the property 'ChoseSomethingFor'
        /// </summary>
        [Fact]
        public void ChoseSomethingForTest()
        {
            // TODO unit test for the property 'ChoseSomethingFor'
        }

        /// <summary>
        /// Test the property 'GeThan'
        /// </summary>
        [Fact]
        public void GeThanTest()
        {
            // TODO unit test for the property 'GeThan'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Gt'
        /// </summary>
        [Fact]
        public void GtTest()
        {
            // TODO unit test for the property 'Gt'
        }

        /// <summary>
        /// Test the property 'Lt'
        /// </summary>
        [Fact]
        public void LtTest()
        {
            // TODO unit test for the property 'Lt'
        }

        /// <summary>
        /// Test the property 'LeThan'
        /// </summary>
        [Fact]
        public void LeThanTest()
        {
            // TODO unit test for the property 'LeThan'
        }

        /// <summary>
        /// Test the property 'EqualTo'
        /// </summary>
        [Fact]
        public void EqualToTest()
        {
            // TODO unit test for the property 'EqualTo'
        }
    }
}
