/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing Or
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Or
        //private Or instance;

        public OrTests()
        {
            // TODO uncomment below to create an instance of Or
            //instance = new Or();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Or
        /// </summary>
        [Fact]
        public void OrInstanceTest()
        {
            // TODO uncomment below to test "IsType" Or
            //Assert.IsType<Or>(instance);
        }

        /// <summary>
        /// Test the property 'Either'
        /// </summary>
        [Fact]
        public void EitherTest()
        {
            // TODO unit test for the property 'Either'
        }

        /// <summary>
        /// Test the property 'VarOr'
        /// </summary>
        [Fact]
        public void VarOrTest()
        {
            // TODO unit test for the property 'VarOr'
        }
    }
}
