/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing Payee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Payee
        //private Payee instance;

        public PayeeTests()
        {
            // TODO uncomment below to create an instance of Payee
            //instance = new Payee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Payee
        /// </summary>
        [Fact]
        public void PayeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Payee
            //Assert.IsType<Payee>(instance);
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'Party'
        /// </summary>
        [Fact]
        public void PartyTest()
        {
            // TODO unit test for the property 'Party'
        }
    }
}
