/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing PlutusCredential
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlutusCredentialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlutusCredential
        //private PlutusCredential instance;

        public PlutusCredentialTests()
        {
            // TODO uncomment below to create an instance of PlutusCredential
            //instance = new PlutusCredential();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlutusCredential
        /// </summary>
        [Fact]
        public void PlutusCredentialInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlutusCredential
            //Assert.IsType<PlutusCredential>(instance);
        }

        /// <summary>
        /// Test the property 'PubKeyCredential'
        /// </summary>
        [Fact]
        public void PubKeyCredentialTest()
        {
            // TODO unit test for the property 'PubKeyCredential'
        }

        /// <summary>
        /// Test the property 'ScriptCredential'
        /// </summary>
        [Fact]
        public void ScriptCredentialTest()
        {
            // TODO unit test for the property 'ScriptCredential'
        }
    }
}
