/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing TokenInAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenInAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenInAccount
        //private TokenInAccount instance;

        public TokenInAccountTests()
        {
            // TODO uncomment below to create an instance of TokenInAccount
            //instance = new TokenInAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenInAccount
        /// </summary>
        [Fact]
        public void TokenInAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenInAccount
            //Assert.IsType<TokenInAccount>(instance);
        }

        /// <summary>
        /// Test the property 'AmountOfToken'
        /// </summary>
        [Fact]
        public void AmountOfTokenTest()
        {
            // TODO unit test for the property 'AmountOfToken'
        }

        /// <summary>
        /// Test the property 'InAccount'
        /// </summary>
        [Fact]
        public void InAccountTest()
        {
            // TODO unit test for the property 'InAccount'
        }
    }
}
