/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionInputTxInterval
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionInputTxIntervalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionInputTxInterval
        //private TransactionInputTxInterval instance;

        public TransactionInputTxIntervalTests()
        {
            // TODO uncomment below to create an instance of TransactionInputTxInterval
            //instance = new TransactionInputTxInterval();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionInputTxInterval
        /// </summary>
        [Fact]
        public void TransactionInputTxIntervalInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionInputTxInterval
            //Assert.IsType<TransactionInputTxInterval>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
    }
}
