/*
 * Marlowe Runtime REST API
 *
 * REST API for Marlowe Runtime
 *
 * The version of the OpenAPI document: 0.0.5.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MarloweAPIClient.Model;
using MarloweAPIClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MarloweAPIClient.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionInput
        //private TransactionInput instance;

        public TransactionInputTests()
        {
            // TODO uncomment below to create an instance of TransactionInput
            //instance = new TransactionInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionInput
        /// </summary>
        [Fact]
        public void TransactionInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionInput
            //Assert.IsType<TransactionInput>(instance);
        }

        /// <summary>
        /// Test the property 'TxInputs'
        /// </summary>
        [Fact]
        public void TxInputsTest()
        {
            // TODO unit test for the property 'TxInputs'
        }

        /// <summary>
        /// Test the property 'TxInterval'
        /// </summary>
        [Fact]
        public void TxIntervalTest()
        {
            // TODO unit test for the property 'TxInterval'
        }
    }
}
